services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao_agro_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: gestao_agro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
